services:
  backend:
    image: ghcr.io/chris-euw/todo-backend:latest
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: ghcr.io/chris-euw/todo-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always